spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///test?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true

logging:
  level:
    com.leo.repository: trace
